# Generated by Django 5.1 on 2024-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application_1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("description", models.CharField(max_length=122)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
