# Generated by Django 5.1 on 2024-09-11 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application_1", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
